### ISSUE TITLE
Feature Request: Custom Workout Creation

### ISSUE THREAD

**Issue by Turtleoo** [bishwasbhatt2/DailyGainz#12]
**Is your feature request related to a user-story? Please describe.**
This is related to user story  number 7, custom workout creation. 

**Describe the solution you'd like**
A new page that allows for the user to create a custom workout.

**Comment by bishwasbhatt2** [comment]
Disclaimer: We had to delete DailyGainz folder on the github, so anyone else pulling changes, make sure to delete DailyGainz and only keep main
