### ISSUE TITLE
Feature Request: Send Email Notifying User

### ISSUE THREAD

**Issue by bishwasbhatt2** [bishwasbhatt2/DailyGainz#8]
**Description**
Try to figure out how to implement a feature that sends an email to the user telling them what workout to do everyday depending on their difficulty

**Comment by Turtleoo** [comment]
Hey Bishwas,
    I might have found a solution to this issue. It's called **Resend** which is an email service that simplifies sending emails from your application. It offers a straightforward API and can be integrated with React applications to send daily emails.

**Comment by bishwasbhatt2** [comment]
Hey Gabriel, 

That sounds like an interesting solution. Let me know how it goes 😃

**Comment by bishwasbhatt2** [comment]
I figured out how to implement SendGrid, so I will make a PR soon
